image:
  repository: jp39/zfs-provisioner
  registry: ghcr.io
  tag: 1.0.0
  pullPolicy: Always
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
provisioner:
  instance: pv.kubernetes.io/zfs
  parentDataset: tank/kubernetes
  parentMountPath: /tank/kubernetes
  nodeName: ''
storageClass:
  create: true
  classes:
    - name: zfs
      policy: Delete
      reserveSpace: true
      annotations:
        storageclass.kubernetes.io/is-default-class: 'true'
env: {}
serviceAccount:
  create: true
  annotations: {}
  name: ''
rbac:
  create: true
resources:
  limits:
    memory: 40Mi
  requests:
    cpu: 50m
    memory: 20Mi
